{"name": "test_case01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test.Testcase object at 0x04496B98>\n\n    def test_case01(self):\n    \n        print('执行用例01.......')\n    \n>       assert 0  # 断言失败\nE       assert 0\n\ntestCase\\test.py:20: AssertionError"}, "start": 1625132930645, "stop": 1625132930646, "uuid": "05dceeab-2a4c-414b-b6ee-2cff92ff7556", "historyId": "9a0b11c2437cbc89147d7c380b2f41d1", "testCaseId": "5da4694bc8c02f9d51b6600c766b0d90", "fullName": "testCase.test.Testcase#test_case01", "labels": [{"name": "parentSuite", "value": "testCase"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "Testcase"}, {"name": "host", "value": "XSD-20190315NRK"}, {"name": "thread", "value": "3544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.test"}]}